### ISSUE TITLE
Swiper Svelte Components

### ISSUE THREAD

**Issue by niklasgrewe** [beomy/svelte-swiper#5]
Hi, thanks for this useful library. I have seen that swiper.js provides [svelte components](https://swiperjs.com/svelte/). Does svelte-swiper use these components for better performance? Are there any big differences between svelte-swiper and the svelte components of swiper.js?

**Comment by beomy** [comment]
svelte-swiper isn't use [svelte components](https://swiperjs.com/svelte/).

It seems that swiperjs@6.3.0 has started official support for svelte.
svelte-swiper was developed before swiperjs@6.3.0.
